apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-auth-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/mongo-auth
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-auth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: mongo-auth-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-auth
  template:
    metadata:
      labels:
        app: mongo-auth
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-auth-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-auth-password
            - name: ADMIN_AUTH_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-auth-password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-auth-pvc
        - name: mongo-init-script
          configMap:
            name: mongo-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init-mongo.sh: |
    #!/bin/bash
    
    until mongosh --host 127.0.0.1 --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
      echo "Aguardando o MongoDB..."
      sleep 1
    done

    mongosh --host 127.0.0.1 <<EOF
      use admin
      db.createUser(
        {
          user: "admin",
          pwd: "$ADMIN_AUTH_PASSWORD",
          roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
        }
      )
      db.auth("admin", "$ADMIN_AUTH_PASSWORD")
    EOF
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo
spec:
  selector:
    app: mongo-auth
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP