apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-requests-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/mongo-requests
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-requests-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: mongo-requests-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-requests-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-requests
  template:
    metadata:
      labels:
        app: mongo-requests
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-requests-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-requests-password
            - name: ADMIN_REQUESTS_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-requests-password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mongo-storage
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  init-mongo.sh: |
    #!/bin/bash
    
    until mongosh --host 127.0.0.1 --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
      echo "Aguardando o MongoDB..."
      sleep 1
    done

    mongosh --host 127.0.0.1 <<EOF
      use admin
      db.createUser(
        {
          user: "admin",
          pwd: "$ADMIN_REQUESTS_PASSWORD",
          roles: [ { role: "userAdminAnyDatabase", db: "admin" } ]
        }
      )
      db.auth("admin", "$ADMIN_REQUESTS_PASSWORD")
    EOF
---
apiVersion: v1
kind: Service
metadata:
  name: requests-mongo
spec:
  selector:
    app: mongo-requests
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
